### ISSUE TITLE
Adding plugin via "Visual Studio Tools for Apache Cordova"

### ISSUE THREAD

**Issue by TioWidow** [afsuarez/mapsforge-cordova-plugin#10]
Hello I am testing the cordova with the "Visual Studio" and I am unable to compile the project after adding the plugin mapsforge, despite the project newly created.

Can you help me identify the error

Severity	Code	Description	Project	File	Line Error		c:\users\NameUser\documents\visual studio 2015\Projects\Test\Test\platforms\android\assets\patterns" 
not located within project!	Test	c:\users\NameUser\documents\visual studio 2015\Projects\Test\Test\MDAVSCLI	1

Version VS2015RC
https://www.visualstudio.com/en-us/features/cordova-vs.aspx

thanks for listening

![image](https://cloud.githubusercontent.com/assets/4378980/8409124/a0e6f064-1e4b-11e5-8824-b57fa8d12d17.png)

**Comment by afsuarez** [comment]
I will download VS2015 and check how to fix it. I've never tried to use it within Visual Studio so maybe I've to prepare it to use other type of folder structure, i don't know.

I will try to give you an answer as soon as possible, hopefully tomorrow, because today I will not have enough time.

**Comment by afsuarez** [comment]
Hello, and sorry for the delay, I couldn't get into this until today.

The problem comes from the *plugin.xml* file. In that file I've specified the path where cordova should place some resources (like those assets, and some images), but for some reason it crashes with relative paths, at least for relative paths that try to get up to the parent folder.

One temporal workaround is to edit the *plugin.xml* file and change the paths of the asset elements to this:

![captura](https://cloud.githubusercontent.com/assets/8784388/8465325/8044cae8-2049-11e5-8e1b-adac9b93af85.PNG)

This way the resources are going to be copied under the ***platforms/android/assets*** folder, so you must then move those resources to the right path. The first three ones that you can see in the image above go to the ***platforms/android/assets*** folder, and the other one, the images, go to ***platforms/android/res/drawable*** folder.

To check that everything is successfully installed you should also check that there are 5 jars under ***platforms/android/libs*** (mapsforge jars and svg jar), and check that the java clases have been placed under ***platforms/android/src/com/suarez/cordova/mapsforge***. 

- To see all folders under your project you have to select the option to the left of the wrench icon.

![captura9](https://cloud.githubusercontent.com/assets/8784388/8465492/f985f8b8-204a-11e5-8f69-815c776bff3d.PNG)
- Then right click over the folder you want to use, and *Include into project* (or something similar).

#### The problem may be a bug in the build process?

*To me all this seems to be like a problem with the build process, not a problem with the plugin. I mean, I've used it in Eclipse and everything worked great, no issues with relative paths. I will see if I can create and compile a Cordova project in VS2013 as it is a more stable/tested IDE.
Another idea that come to my mind is that maybe since the last time I used cordova they have update it, so now it is forbidden to use relative paths within the plugin.xml to access parent folders.*

### Another problem [Ripple.js]
After doing all that and being able to compile the newly created project, I added a call to the plugin (`mapsforge.plugin.status();`) and the I executed it with the android emulator and also with Ripple. The result...the plugin fails due to *ripple.js*:

![captura2](https://cloud.githubusercontent.com/assets/8784388/8465820/268f85a2-204d-11e5-91c7-abcbd9da372f.PNG)

It says that it can not read the property *global-status* even though *global-status* is not a property, it is just a plain string that is going to be compared to choose the method to execute... I don't know, it is kinda weird. Maybe in an actual device *ripple.js* is not used and everything works fine, I don't know, I will take a look at that another day.

**Comment by afsuarez** [comment]
Should be fixed now.
