### ISSUE TITLE
Map file not found

### ISSUE THREAD

**Issue by egofree71** [afsuarez/mapsforge-cordova-plugin#11]
Hello,

I try to use the plugin with the Ionic framework. When i run it in the android emulator with genymotion, i've always the same error message in the console : 'Map file not found'. Here is the code in the controller :

  $ionicPlatform.ready(function() {

      var mapfile = "/sdcard/Download/albania.map";

      // initialize the map on the "map" div with a given center and zoom
      var map = L.map('map', {
          center: [41.328341,19.818761],
          zoom: 9
      });

      mapsforge.cache.initialize(mapfile,
          function() {
              console.log("map file loaded");
              L.offlineTileLayer({
                  maxZoom: 18,
                  attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
              }).addTo(map);

          },
          function(error) {
              console.log("error loading map file: " + mapfile);
              console.dir("error:" + error);
          });
}

I've uploaded the 'map into the download folder by dragging the file into the emulator, and i can see the file in the file manager of the emulator. I tested many different paths  (for instance /storage/emulated/0/Download/albania.map, /sdcard/Download/albania.map, etc.), but the plugin never finds the map file . Also by default, the map is stored within my project in the www/data folder. So i tried also '/android_asset/www/data' or 'file:///android_asset/www/data' folders, but it's not working. 
Do you have any idea how to specify the folder ?

**Comment by afsuarez** [comment]
Hello.
I've been checking it out and I could load the map (I put an alert in both callback functions to see if it was working).

![Emulator](https://cloud.githubusercontent.com/assets/8784388/8786282/7c044f1a-2f2d-11e5-98e5-5f7ed55c6761.PNG)

I placed the file under /storage/sdcard, as you can see below:

![DDMS](https://cloud.githubusercontent.com/assets/8784388/8786305/a2333070-2f2d-11e5-8fe4-de4554fac369.PNG)

If you place it under 'Download' for example, try ``/storage/sdcard/Download/albania.map`` or ``/mnt/sdcard/Download/albania.map``.

The way it is done in the code is like this:

![SetMapFileMethod](https://cloud.githubusercontent.com/assets/8784388/8786377/0f0d0b94-2f2e-11e5-92c3-d2a46d246a22.PNG)

So the path you pass is the path it is going to look for.

#### WWW folder

Abour placing it under the ``www`` folder....I don't know, I mean, I'm not sure how cordova packages that folder so trying to guess its path it is going to be difficult. If you want to include the map in your application from the begining I would place it under the ``www`` and then through javascript load it from that folder and save it to the android filesystem with the File API plugin (since I guess you will be able to get the file with a simple path like ``js/albania.map`` or ``data/albania.map`` like you would do to get CSS or JS files).

**Comment by egofree71** [comment]
Thanks for your help.

**Comment by egofree71** [comment]
I've worked again on this problem, and i've finally found a solution. I write my results here, as it could be useful for others. First, it's not possible for security reason to access directly files stored in the project folder : 
"Chrome requires --allow-file-access-from-files run argument to support API via file:/// protocol."

https://github.com/apache/cordova-plugin-file

A solution is to download and store the map in the /Download folder of the sdCard (/mnt/sdcard/Download/albania.map)
Then i had another problem : i had an error message concerning a callback function, and i've found that the problem comes from the leaflet version. I used the stable version 0.7.3, but if you use a newer version (1.0.0 beta or dev version), the problem is gone. I leave the issue open right now for feedback.
